# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Inicio"
  url = "#about"
  weight = 10

[[main]]
  name = "Habilidades"
  url = "#skills"
  weight = 20

[[main]]
  name = "Destacado"
  url = "#featured"
  weight = 30

[[main]]
  name = "YouTube"
  url = "#posts"
  weight = 40

[[main]]
  name = "Publicaciones"
  url = "publication/"
  weight = 50

  [[main]]
    identifier = "people"
    name = "Equipo"
    url = "team/"
    weight = 60

  [[main]]
    identifier = "people1"
    name = "Investigadores"
    url = "team/#researchers"
    parent = "people"
    weight = 60

  [[main]]
    identifier = "people2"
    name = "Estudiantes"
    url = "team/#students"
    parent = "people"
    weight = 62

  [[main]]
    identifier = "people3"
    name = "Colaboraciones"
    url = "colabs/"
    parent = "people"
    weight = 65

  [[main]]
    identifier = "resume"
    name = "Trayectoria"
    url = "profile/"
    weight = 70

  [[main]]
    identifier = "resume1"
    name = "Experiencia"
    url = "profile/#experience"
    parent = "resume"
    weight = 70

  [[main]]
    identifier = "resume2"
    name = "Logros"
    url = "profile/#accomplishments"
    parent = "resume"
    weight = 75

[[main]]
  name = "Contacto"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "/es/files/JDL_CV_es.pdf"
    weight = 90
